# This is a basic workflow to help you get started with Actions

name: CI to Docker Hub

# Controls when the workflow will run
on:
  # Trigger the workflow on push event but only for the main branch
  push:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@TrevorMuchenje

      # Runs a single command using the runners shell
      - name: Login to Docker Hub
        uses: docker/login-action@trevormuchenje
        with:
          username: ${{ secrets.TREVORMUCHENJE }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@trevormuchenje
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@TrevorMuchenje
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
